import 'package:acolherconsultas/modules/consultas/models/consulta.dart';
import 'package:acolherconsultas/modules/pacientes/models/paciente.dart';

final Paciente pacienteTeste = Paciente(
  nome: 'João Silva',
  ativo: true,
  cpf: '123.456.789-00',
  rg: '1234567',
  numeroCartaoSus: '123456789012345',
  dataNasc: DateTime(1980, 5, 15),
  sexo: 'Masculino',
  motivoAcolhimento: 'Dor de cabeça persistente',
  localAcolhimentoAnterior: 'Maria Paola',
  casaDeApoioId: 'abc123', 
  nomeMae: '', 
  cidadeOrigem: '',
  acolhimentoAnterior: false, 
  nomeEscola: '',
);

final ConsultaCadastro consultaTeste = ConsultaCadastro(
  casaDeApoioId: "casaDeApoio123",
  pacienteId: "paciente456",
  dataHorario: DateTime.now(),
  estado: "em andamento",
  dadosConsulta: Consulta(
    cuidadorPrincipal: "Maria Silva",
    queixaPrincipal: "Dor abdominal",
    descricao: "Paciente relata dor há 3 dias.",
    refeicoesComTecnologia: 2,
    refeicoesDuranteODia: "Café da manhã, almoço, jantar",
    consumiuFeijao: 1,
    consumiuFrutas: 1,
    consumiuVerdurasLegumes: 1,
    consumiuEmbutidos: 0,
    consumiuBebidasAdocicadas: 1,
    consumiuMacarraoInstantaneoSalgado: 0,
    consumiuBiscoitoRecheado: 0,
    ingestaoHidrica: "2 litros",
    suplementacao: "Nenhuma",
    diurese: "Normal",
    evacuacoes: "1 vez ao dia",
    itensHigiene: "Escova de dente, sabonete",
    higieneCorporal: "Normal",
    higieneBucal: "Normal",
    sono: "8 horas por noite",
    comprimento: 120,
    peso: 30.5,
    comprimentoPorIdade: 50,
    imcPorIdade: 60,
    frequenciaCardiaca: "80 bpm",
    saturacao: "98%",
    auscultaCardiaca: "Normal",
    auscultaPulmonar: "Normal",
    pressaoArterial: "120/80 mmHg",
    temperatura: 36.5,
    otoscopia: "Normal",
    orofaringe: "Normal",
    avaliacaoMuscoesqueletica: "Normal",
    avaliacaoPele: "Sem lesões",
    marcosPresentes: "Caminhar, falar",
    marcosAusentes: "Nenhum",
    comoSeSenteHoje: "Bem",
    analiseGeral: "Saudável",
    avaliacoes: "Rotina",
    intervencoes: "Nenhuma",
  ),
);