import 'package:acolherconsultas/modules/consultas/models/consulta.dart';
import 'package:acolherconsultas/modules/pacientes/models/paciente.dart';

final Paciente pacienteTeste = Paciente(
  nome: 'João Silva',
  ativo: true,
  cpf: '123.456.789-00',
  rg: '1234567',
  numeroCartaoSus: '123456789012345',
  dataNasc: DateTime(1980, 5, 15),
  sexo: 'Masculino',
  motivoAcolhimento: 'Dor de cabeça persistente',
  localAcolhimentoAnterior: 'Maria Paola',
  casaDeApoioId: 'abc123',
  nomeMae: '',
  cidadeOrigem: '',
  acolhimentoAnterior: false,
  nomeEscola: '',
);

final ConsultaCadastro consultaTeste = ConsultaCadastro(
  id: "consulta789",
  casaDeApoioId: "casaDeApoio123",
  pacienteNome: "João Pereira",
  pacienteId: "paciente456",
  dataHorario: DateTime.now(),
  estado: "em andamento",
  dadosConsulta: Consulta(
    cuidadorPrincipal: "Maria Silva",
    queixaPrincipal: "Dor abdominal",
    descricao: "Paciente relata dor há 3 dias.",
    observacoesPaciente: "Paciente colaborativo e responde bem às perguntas.",
    refeicoesComTecnologia: "Sim",
    refeicoesDuranteODia: "Café da manhã, almoço, jantar",
    consumiuFeijao: "Sim",
    consumiuFrutas: "Sim",
    consumiuVerdurasLegumes: "Sim",
    consumiuEmbutidos: "Sim",
    consumiuBebidasAdocicadas: "Sim",
    consumiuMacarraoInstantaneoSalgado: "Sim",
    consumiuBiscoitoRecheado: "Sim",
    ingestaoHidrica: "2 litros",
    suplementacao: "Nenhuma",
    diurese: "Normal",
    evacuacoes: "1 vez ao dia",
    itensHigiene: "Escova de dente, sabonete",
    higieneCorporal: "Normal",
    higieneBucal: "Normal",
    sono: "8 horas por noite",
    comprimento: 120,
    peso: 30.5,
    comprimentoPorIdade: "Adequado",
    imcPorIdade: "Eutrofia",
    frequenciaCardiaca: "80 bpm",
    saturacao: "98%",
    auscultaCardiaca: "Normal",
    auscultaPulmonar: "Normal",
    pressaoArterial: "120/80 mmHg",
    temperatura: 36.5,
    otoscopia: "Normal",
    orofaringe: "Normal",
    avaliacaoMuscoesqueletica: "Normal",
    avaliacaoPele: "Sem lesões",
    marcosPresentes: "Caminhar, falar",
    marcosAusentes: "Nenhum",
    observacoesDesenvolvimento: "Desenvolvimento adequado para idade.",
    comoSeSenteHoje: "Bem",
    observacoesPsicoemocionais: "Estável emocionalmente.",
    analiseGeral: "Saudável",
    avaliacoes: "Rotina",
    intervencoes: "Nenhuma",
    fontanelas: "Moleira fechada",
    cotoUmbilical: "Sem alterações",
    genitalia: "Normal",
    frequenciaRespiratoria: "20 rpm",
    bregmatica: 2,
    bregmaticaCalcificada: true,
    lambdoide: 1,
    lambdoideCalcificada: false,
    avaliacaoLinguagem: "Boa",
    reflexoBusca: "P",
    reflexoSuccao: "P",
    reflexoPreensaoPalmar: "P",
    reflexoPreensaoPlantar: "P",
    reflexoBabinski: "P",
    reflexoTonicoCervical: "P",
    reflexoMoro: "P",
    reflexoMarcha: "P",
    reflexoPiscarOptico: "P",
    reflexoBuscaESuccao: "P",
    movimentosSimetricosFaciais: "P",
    reflexoPiscarAcustico: "P",
    reflexoVomito: "P",
    aperteNariz: "P",
    atividadesLazer: "Futebol, leitura",
    identidadeGenero: "Cisgenero",
    sexualidade: "Homossexual",
    estagioTurnerMeninasMamas: "M1",
    estagioTurnerMeninasPelosPubianos: "P3",
    dataUltimaMenstruacao: DateTime(2024, 10, 1),
    fluxoMenstrual: "Moderado",
    regularidadeMenstruacao: "Regular",
    quaoIrregular: "Levemente irregular",
    dimenorreia: "Presente",
    usoAbsorvente: "Usa diariamente",
    usaMedicamento: "Sim",
    qualMedicamento: "Nenhum",
    observacoesSaudeSexualEReprodutivaMeninas: "Sem queixas",
    vidaSexualAtiva: "Sim",
    usaMetodoContraceptivo: "Nao",
    qualMetodoContraceptivo: "Nenhum",
    jaFezPreventivo: "Sim",
    quandoFezPreventivo: DateTime(2024, 9, 1),
    seMasturba: "Sim",
    frequenciaMasturbacao: "Raramente",
    estagioTurnerMeninosGenitalia: "G1",
    estagioTurnerMeninosPelosPubianos: "P2",
    semenarca: "Sim",
    quandoSemenarca: DateTime(2024, 10, 1),
    analiseGeralCasa: "Casa em boas condições",
    exameFisicoCasa: "Limpeza adequada",
    avaliacoesCasa: "Nenhuma observação relevante",
    oriParaCuidador: "Manter alimentação equilibrada",
    oriParaPaciente: "Praticar atividades físicas",
    oriParaCoordenacao: "Manter acompanhamento regular",
  ),
);
