import 'package:acolherconsultas/modules/consultas/models/consulta.dart';
import 'package:acolherconsultas/modules/pacientes/models/paciente.dart';

final Paciente pacienteTeste = Paciente(
  nome: 'João Silva',
  ativo: true,
  cpf: '123.456.789-00',
  rg: '1234567',
  numeroCartaoSus: '123456789012345',
  dataNasc: DateTime(1980, 5, 15),
  sexo: 'Masculino',
  motivoAcolhimento: 'Dor de cabeça persistente',
  localAcolhimentoAnterior: 'Maria Paola',
  casaDeApoioId: 'abc123',
  nomeMae: '',
  cidadeOrigem: '',
  acolhimentoAnterior: false,
  nomeEscola: '',
);

final ConsultaCadastro consultaTeste = ConsultaCadastro(
  id: "consulta789",
  casaDeApoioId: "casaDeApoio123",
  pacienteNome: "João Pereira",
  pacienteId: "paciente456",
  dataHorario: DateTime.now(),
  estado: "em andamento",
  dadosConsulta: Consulta(
    cuidadorPrincipal: "Maria Silva",
    queixaPrincipal: "Dor abdominal",
    descricao: "Paciente relata dor há 3 dias.",
    observacoesPaciente: "Paciente colaborativo e responde bem às perguntas.",
    refeicoesComTecnologia: 2,
    refeicoesDuranteODia: "Café da manhã, almoço, jantar",
    consumiuFeijao: 1,
    consumiuFrutas: 1,
    consumiuVerdurasLegumes: 1,
    consumiuEmbutidos: 0,
    consumiuBebidasAdocicadas: 1,
    consumiuMacarraoInstantaneoSalgado: 0,
    consumiuBiscoitoRecheado: 0,
    ingestaoHidrica: "2 litros",
    suplementacao: "Nenhuma",
    diurese: "Normal",
    evacuacoes: "1 vez ao dia",
    itensHigiene: "Escova de dente, sabonete",
    higieneCorporal: "Normal",
    higieneBucal: "Normal",
    sono: "8 horas por noite",
    comprimento: 120,
    peso: 30.5,
    comprimentoPorIdade: 50,
    imcPorIdade: 60,
    frequenciaCardiaca: "80 bpm",
    saturacao: "98%",
    auscultaCardiaca: "Normal",
    auscultaPulmonar: "Normal",
    pressaoArterial: "120/80 mmHg",
    temperatura: 36.5,
    otoscopia: "Normal",
    orofaringe: "Normal",
    avaliacaoMuscoesqueletica: "Normal",
    avaliacaoPele: "Sem lesões",
    marcosPresentes: "Caminhar, falar",
    marcosAusentes: "Nenhum",
    observacoesDesenvolvimento: "Desenvolvimento adequado para idade.",
    comoSeSenteHoje: "Bem",
    observacoesPsicoemocionais: "Estável emocionalmente.",
    analiseGeral: "Saudável",
    avaliacoes: "Rotina",
    intervencoes: "Nenhuma",
    fontanelas: "Moleira fechada",
    cotoUmbilical: "Sem alterações",
    genitalia: "Normal",
    frequenciaRespiratoria: "20 rpm",
    bregmatica: 2,
    bregmaticaCalcificada: true,
    lambdoide: 1,
    lambdoideCalcificada: false,
    avaliacaoLinguagem: "Boa",
    reflexoBusca: 2,
    reflexoSuccao: 3,
    reflexoPreensaoPalmar: 3,
    reflexoPreensaoPlantar: 2,
    reflexoBabinski: 3,
    reflexoTonicoCervical: 3,
    reflexoMoro: 2,
    reflexoMarcha: 3,
    reflexoPiscarOptico: 2,
    reflexoBuscaESuccao: 3,
    movimentosSimetricosFaciais: 2,
    reflexoPiscarAcustico: 3,
    reflexoVomito: 2,
    aperteNariz: 1,
    atividadesLazer: "Futebol, leitura",
    identidadeGenero: 1,
    sexualidade: 2,
    estagioTurnerMeninasMamas: 2,
    estagioTurnerMeninasPelosPubianos: 1,
    dataUltimaMenstruacao: DateTime(2024, 10, 1),
    fluxoMenstrual: 2,
    regularidadeMenstruacao: 1,
    quaoIrregular: "Levemente irregular",
    dimenorreia: true,
    usoAbsorvente: "Usa diariamente",
    usaMedicamento: false,
    qualMedicamento: "Nenhum",
    observacoesSaudeSexualEReprodutivaMeninas: "Sem queixas",
    vidaSexualAtiva: false,
    usaMetodoContraceptivo: false,
    qualMetodoContraceptivo: "Nenhum",
    jaFezPreventivo: false,
    quandoFezPreventivo: DateTime(2024, 9, 1),
    seMasturba: false,
    frequenciaMasturbacao: "Raramente",
    estagioTurnerMeninosGenitalia: 1,
    estagioTurnerMeninosPelosPubianos: 1,
    semenarca: false,
    quandoSemenarca: DateTime(2024, 10, 1),
    analiseGeralCasa: "Casa em boas condições",
    exameFisicoCasa: "Limpeza adequada",
    avaliacoesCasa: "Nenhuma observação relevante",
    oriParaCuidador: "Manter alimentação equilibrada",
    oriParaPaciente: "Praticar atividades físicas",
    oriParaCoordenacao: "Manter acompanhamento regular",
  ),
);
